spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8080}

db:
  url: jdbc:mysql://localhost:3306/codedrinker?allowMultiQueries=true
  username: root
  password: root


