spring:
  thymeleaf:
    mode: HTML5
  mvc:
    favicon:
      enabled: false
logging:
  level:
    org:
      springframework: error
server:
  port: ${PORT:5000}

db:
  url: ${JDBC_DATABASE_URL}
  username: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
  driver: com.mysql.jdbc.Driver
github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}


