spring:
  thymeleaf:
    mode: HTML5
  mvc:
    favicon:
      enabled: false
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8080}

db:
  url: jdbc:h2:~/commenthub
  username: sa
  password: sa
  driver: org.h2.Driver
github:
  client:
    id: 17546a09800f4728827f
    secret: de5c445d7da2165ce1318376b0b20b0677eb0940
